apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: {{ .Values.orders.replicas }}
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: {{ .Values.orders.image }}
          ports:
            - containerPort: {{ .Values.orders.grpc_port }}