apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: {{ .Values.orders.grpc_port }}
      targetPort: {{ .Values.orders.grpc_port }}