apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
  selector:
    app: customers
  ports:
    - protocol: TCP
      port: {{ .Values.customers.grpc_port }}
      targetPort: {{ .Values.customers.grpc_port }}