apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: {{ .Values.payments.replicas }}
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: {{ .Values.payments.image }}
          ports:
            - containerPort: {{ .Values.payments.grpc_port }}
