storage:
  path: "storage"
database:
  host: pgsql
  port: 5432
  user: postgres
  password: password
  db: products
grpc_server:
  host: 0.0.0.0
  port: 50056
  timeout: 30
file_server:
  host: 0.0.0.0
  port: 8081
  timeout: 30
paginator:
  limit: 20
slack:
  # webhook_url: "https://hooks.slack.com/services/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"
  webhook_url: ""
  channel: "testing"
  username: "incoming-webhook"

services:
  admin:
    host: admins
    port: 50051
