apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: {{ .Values.api_gateway.grpc_port }}
      targetPort: {{ .Values.api_gateway.grpc_port }}