apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: {{ .Values.rabbitmq.amqp_protocol_port }}
    - name: amqp-interface
      protocol: TCP
      port: {{ .Values.rabbitmq.amqp_interface_port }}
